# Generated by Django 2.0.1 on 2018-02-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='stop',
            field=models.DateTimeField(null=True),
        ),
    ]
